logging:
    config: classpath:logback-spring.xml
publibKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAubaU1FhehBtgYWz1nFlaybYjWfxNXbsJmcWMNrUWmzv/YKcbV7Sy/C8ep+5MT/yWuXKR7yrmb+TrNs7dii7FKNyVXBC4BZXemc1sVMDp4jcRyrpvjyamdazrLup8Zfq4aH63Tu5vevcV5kos+67ujg7clThvaNxwpp+t4xxh0B4RryhkOboexZOLlo9i99TWZlQjuctIMGxJPCEXD+caOn1yqbFnh8M+vxlopZaqj6xexau0lTPeWEZIjndz92Ae4gDuzSgLmU3FlRcdbS1hU0rUoup4cmIjNYmwTiOQZEZaG/lN58iOXnSTY0J9aPav0S9MZqMHv+8qi03KeDCdxQIDAQAB
server:
    port: 8005
spring:
    application:
        name: clinicPrescription
