package cn.project.bean;

import java.math.BigDecimal;
import java.util.Date;

public class ItripHotelOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.id
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.userId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.orderType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer ordertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.orderNo
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.tradeNo
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String tradeno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.hotelId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Long hotelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.hotelName
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String hotelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.roomId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Long roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.count
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.bookingDays
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer bookingdays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.checkInDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Date checkindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.checkOutDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Date checkoutdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.orderStatus
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.payAmount
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private BigDecimal payamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.payType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.noticePhone
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String noticephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.noticeEmail
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String noticeemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.isNeedInvoice
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer isneedinvoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.invoiceType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer invoicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.invoiceHead
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String invoicehead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.linkUserName
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String linkusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.bookType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Integer booktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.creationDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.createdBy
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.modifyDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.modifiedBy
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private Long modifiedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_order.specialRequirement
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    private String specialrequirement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.id
     *
     * @return the value of itrip_hotel_order.id
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.id
     *
     * @param id the value for itrip_hotel_order.id
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.userId
     *
     * @return the value of itrip_hotel_order.userId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.userId
     *
     * @param userid the value for itrip_hotel_order.userId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.orderType
     *
     * @return the value of itrip_hotel_order.orderType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.orderType
     *
     * @param ordertype the value for itrip_hotel_order.orderType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.orderNo
     *
     * @return the value of itrip_hotel_order.orderNo
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.orderNo
     *
     * @param orderno the value for itrip_hotel_order.orderNo
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.tradeNo
     *
     * @return the value of itrip_hotel_order.tradeNo
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getTradeno() {
        return tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.tradeNo
     *
     * @param tradeno the value for itrip_hotel_order.tradeNo
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setTradeno(String tradeno) {
        this.tradeno = tradeno == null ? null : tradeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.hotelId
     *
     * @return the value of itrip_hotel_order.hotelId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.hotelId
     *
     * @param hotelid the value for itrip_hotel_order.hotelId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.hotelName
     *
     * @return the value of itrip_hotel_order.hotelName
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.hotelName
     *
     * @param hotelname the value for itrip_hotel_order.hotelName
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.roomId
     *
     * @return the value of itrip_hotel_order.roomId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.roomId
     *
     * @param roomid the value for itrip_hotel_order.roomId
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.count
     *
     * @return the value of itrip_hotel_order.count
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.count
     *
     * @param count the value for itrip_hotel_order.count
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.bookingDays
     *
     * @return the value of itrip_hotel_order.bookingDays
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getBookingdays() {
        return bookingdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.bookingDays
     *
     * @param bookingdays the value for itrip_hotel_order.bookingDays
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setBookingdays(Integer bookingdays) {
        this.bookingdays = bookingdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.checkInDate
     *
     * @return the value of itrip_hotel_order.checkInDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Date getCheckindate() {
        return checkindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.checkInDate
     *
     * @param checkindate the value for itrip_hotel_order.checkInDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setCheckindate(Date checkindate) {
        this.checkindate = checkindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.checkOutDate
     *
     * @return the value of itrip_hotel_order.checkOutDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Date getCheckoutdate() {
        return checkoutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.checkOutDate
     *
     * @param checkoutdate the value for itrip_hotel_order.checkOutDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setCheckoutdate(Date checkoutdate) {
        this.checkoutdate = checkoutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.orderStatus
     *
     * @return the value of itrip_hotel_order.orderStatus
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.orderStatus
     *
     * @param orderstatus the value for itrip_hotel_order.orderStatus
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.payAmount
     *
     * @return the value of itrip_hotel_order.payAmount
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public BigDecimal getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.payAmount
     *
     * @param payamount the value for itrip_hotel_order.payAmount
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.payType
     *
     * @return the value of itrip_hotel_order.payType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.payType
     *
     * @param paytype the value for itrip_hotel_order.payType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.noticePhone
     *
     * @return the value of itrip_hotel_order.noticePhone
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getNoticephone() {
        return noticephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.noticePhone
     *
     * @param noticephone the value for itrip_hotel_order.noticePhone
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setNoticephone(String noticephone) {
        this.noticephone = noticephone == null ? null : noticephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.noticeEmail
     *
     * @return the value of itrip_hotel_order.noticeEmail
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getNoticeemail() {
        return noticeemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.noticeEmail
     *
     * @param noticeemail the value for itrip_hotel_order.noticeEmail
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setNoticeemail(String noticeemail) {
        this.noticeemail = noticeemail == null ? null : noticeemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.isNeedInvoice
     *
     * @return the value of itrip_hotel_order.isNeedInvoice
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getIsneedinvoice() {
        return isneedinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.isNeedInvoice
     *
     * @param isneedinvoice the value for itrip_hotel_order.isNeedInvoice
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setIsneedinvoice(Integer isneedinvoice) {
        this.isneedinvoice = isneedinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.invoiceType
     *
     * @return the value of itrip_hotel_order.invoiceType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getInvoicetype() {
        return invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.invoiceType
     *
     * @param invoicetype the value for itrip_hotel_order.invoiceType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setInvoicetype(Integer invoicetype) {
        this.invoicetype = invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.invoiceHead
     *
     * @return the value of itrip_hotel_order.invoiceHead
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getInvoicehead() {
        return invoicehead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.invoiceHead
     *
     * @param invoicehead the value for itrip_hotel_order.invoiceHead
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setInvoicehead(String invoicehead) {
        this.invoicehead = invoicehead == null ? null : invoicehead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.linkUserName
     *
     * @return the value of itrip_hotel_order.linkUserName
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getLinkusername() {
        return linkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.linkUserName
     *
     * @param linkusername the value for itrip_hotel_order.linkUserName
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setLinkusername(String linkusername) {
        this.linkusername = linkusername == null ? null : linkusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.bookType
     *
     * @return the value of itrip_hotel_order.bookType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Integer getBooktype() {
        return booktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.bookType
     *
     * @param booktype the value for itrip_hotel_order.bookType
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setBooktype(Integer booktype) {
        this.booktype = booktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.creationDate
     *
     * @return the value of itrip_hotel_order.creationDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.creationDate
     *
     * @param creationdate the value for itrip_hotel_order.creationDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.createdBy
     *
     * @return the value of itrip_hotel_order.createdBy
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.createdBy
     *
     * @param createdby the value for itrip_hotel_order.createdBy
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.modifyDate
     *
     * @return the value of itrip_hotel_order.modifyDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.modifyDate
     *
     * @param modifydate the value for itrip_hotel_order.modifyDate
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.modifiedBy
     *
     * @return the value of itrip_hotel_order.modifiedBy
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.modifiedBy
     *
     * @param modifiedby the value for itrip_hotel_order.modifiedBy
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_order.specialRequirement
     *
     * @return the value of itrip_hotel_order.specialRequirement
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public String getSpecialrequirement() {
        return specialrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_order.specialRequirement
     *
     * @param specialrequirement the value for itrip_hotel_order.specialRequirement
     *
     * @mbg.generated Sat Dec 28 13:41:43 CST 2019
     */
    public void setSpecialrequirement(String specialrequirement) {
        this.specialrequirement = specialrequirement == null ? null : specialrequirement.trim();
    }
}